# Generated by Django 6.0 on 2025-12-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Journal App', max_length=100)),
                ('maintenance_mode', models.BooleanField(default=False, help_text='If active, only admins can access the site.')),
                ('allow_registration', models.BooleanField(default=True)),
                ('welcome_message', models.TextField(default='Welcome to your personal secure journal.')),
            ],
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Journal Entries'},
        ),
    ]
